"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnyDecorator = (...args) => { };
exports.Realname = () => exports.AnyDecorator;
exports.Uuid = () => exports.AnyDecorator;
exports.Boolean = () => exports.AnyDecorator;
exports.Words = () => exports.AnyDecorator;
exports.Word = () => exports.AnyDecorator;
exports.Number = () => exports.AnyDecorator;
exports.Phone = () => exports.AnyDecorator;
exports.Color = () => exports.AnyDecorator;
exports.Ip = () => exports.AnyDecorator;
exports.Avatar = () => exports.AnyDecorator;
exports.Image = () => exports.AnyDecorator;
exports.CompanyName = () => exports.AnyDecorator;
exports.SecondaryAddress = () => exports.AnyDecorator;
exports.StreetAddress = () => exports.AnyDecorator;
exports.StreetName = () => exports.AnyDecorator;
exports.Country = () => exports.AnyDecorator;
exports.County = () => exports.AnyDecorator;
exports.Lng = () => exports.AnyDecorator;
exports.Lat = () => exports.AnyDecorator;
exports.ProductName = () => exports.AnyDecorator;
exports.Price = () => exports.AnyDecorator;
exports.Content = () => exports.AnyDecorator;
exports.Desc = () => exports.AnyDecorator;
exports.Title = () => exports.AnyDecorator;
exports.CardId = () => exports.AnyDecorator;
exports.Password = () => exports.AnyDecorator;
exports.Mac = () => exports.AnyDecorator;
exports.Email = () => exports.AnyDecorator;
exports.UserName = () => exports.AnyDecorator;
exports.DepartmentName = () => exports.AnyDecorator;
/**
 * 数据库关系
 */
exports.PrimaryGeneratedColumn = () => exports.AnyDecorator;
exports.PrimaryColumn = () => exports.AnyDecorator;
exports.ObjectID = () => exports.AnyDecorator;
exports.CreateDate = () => exports.AnyDecorator;
exports.UpdateDate = () => exports.AnyDecorator;
exports.ManyToOne = () => exports.AnyDecorator;
exports.OneToMany = () => exports.AnyDecorator;
exports.ManyToMany = () => exports.AnyDecorator;
exports.Entity = () => exports.AnyDecorator;
exports.Tree = () => exports.AnyDecorator;
exports.TreeParent = () => exports.AnyDecorator;
exports.TreeChildren = () => exports.AnyDecorator;
